# Generated by Django 5.2.11 on 2026-02-10 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_rename_created_at_document_uploaded_at_and_more'),
        ('documents', '0004_install_vector_extension'),
    ]

    operations = [
    ]
