# Generated by Django 5.2.11 on 2026-02-10 19:59

import pgvector.django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_merge_20260210_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='embedding',
            field=pgvector.django.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
